superfaceai/one-sdk

- .github/workflows/ci_cd.yml
- .github/workflows/release.yml
For CI/CD pipeline, core/target is restored from cache. It contains only release build of dependencies, so they are rebuilt for every CI/CD run.
By splitting cache, it should be avoided.
> Split cache for cargo

- host/js/src/cloudflare/index.ts
- host/js/src/node/index.ts
- adds `sdkAuthToken` to node.js and Cloudflare client.
I am keeping `sdkAuthToken` to keep it same as for original OneSDK. Same for CF Worker, not to name same thing with different names.
> Add sdkAuthToken as client option

- core/Cargo.lock
- core/core/Cargo.toml
- core/core/src/bindings.rs
- core/core/src/lib.rs
- core/core/src/sf_core.rs
- core/core/src/sf_core/cache.rs
- core/core/src/sf_core/map_std_impl.rs
- core/core/src/sf_core/profile_validator.rs
- core/core_to_map_std/Cargo.toml
- core/host_to_core_std/Cargo.toml
- core/host_to_core_std/src/abi/exchange.rs
- core/host_to_core_std/src/abi/mod.rs
- core/host_to_core_std/src/lib.rs
- core/host_to_core_std/src/unstable/fs.rs
- core/host_to_core_std/src/unstable/http.rs
- core/host_to_core_std/src/unstable/mod.rs
- core/host_to_core_std/src/unstable/perform.rs
- core/host_to_core_std/src/unstable/stream.rs
- core/host_to_core_std/src/unstable/value.rs
- core/interpreter_js/Cargo.toml
* inspired by rust allocator API, calls against message exchange FFI and stream exchange FFI can be replaced by custom implementation/closure, mainly in tests
* run cargo fmt
See this test for an example on how this improves testability: https://github.com/superfaceai/one-sdk/pull/19/files#diff-bb06d5ff668217765af2c523f4b6e6972eef329c45f3436d112c4a670d0f1370R213
> make host_to_core std more testable

- host/js/package.json
- host/js/src/common/app.ts
- host/js/src/node/index.ts
- host/js/yarn.lock
Node.js typings doesn't include version property, so We had to cast option to any. 
I also limited supported Node.js versions to active in july 2023
And updated dependencies to latests.
> Allow to use Node.js 20 with TypeScript

- .github/workflows/ci_cd.yml
- Makefile
- core/core/src/observability/mod.rs
- host/js/src/node/index.ts
* install python host as editable package in `make deps_host_py`
* trace when metrics buffer is gotten and cleared
* remove unused variables from node InternalClient
* remove unneeded dependecy install step from python cicd
> feat: small tweaks across the project

- core/core/src/observability/metrics.rs
- core/core/src/observability/mod.rs
- core/core/src/sf_core.rs
- core/core/src/sf_core/exception.rs
- host/js/src/node/index.test.ts
- host/python/src/one_sdk/app.py
- host/python/src/one_sdk/platform.py
- host/python/tests/test_one_client.py
* if a profile file was not found two things happened
* the error generated was not correctly propagated to the host
* the bad path was triggering another bug, causing recovery to crash
* also added more information into the PanicData metric to improve usefulness of dev log
> fix: document cache file not found errors

- core/core/src/sf_core.rs
- core/interpreter_js/src/lib.rs
* take map filename from the url and send it to the interpreter to be included in a potential stacktrace
* in the future the map name should be taken from the map manifest
related to #66
stacktrace example (python)
```
one_sdk.error.UnexpectedError: JsInterpreterError: Code evaluation failed: Uncaught ReferenceError: 'console' is not defined
at Example (wasm-sdk.example.localhost.map.js:13)
at _start (map_std.js:373)
at <eval> ()
```
> feat: improve js map stacktrace

- README.md
- docs/CONTRIBUTING.md
- host/javascript/README.md
- host/python/README.md
Update all READMEs and contributing guide to replace references to Discord with GitHub discussions and support page.
> docs: Replace refs to Discord w/ GH Discussions

- core/core/src/observability/mod.rs
- core/interpreter_js/src/core_to_map_bindings/mod.rs
* JsValueDebug was cutting long strings at non-char boundaries accidentally
* dev log dump now includes `@metrics` target
There was an issue with the JsValueDebug printing that if the string was too long and was cut to MAX_SHOWN len for logging this could fall inside an UTF8 char and cause a panic.
Also panics were not being included in dev log dump.
> fix: JsValueDebug cutting string at non-char boundary

- core/Cargo.lock
- core/core/src/sf_core/json_schema_validator.rs
- core/json_schemas/Cargo.toml
- core/json_schemas/src/main.rs
- core/json_schemas/src/schemas/security_values.json
- core/json_schemas/tests/common/mod.rs
- core/json_schemas/tests/security_values_test.rs
When I was fixing Security Values validation, I realized, that testing schema as part of JSON Schema validator isn't best place. 
In this PR, I moved tests to the `json_schema` module.
The open question is, if tests should translate YAML to JSON, or just use JSON which is present.
> Move json schema test next to schemas

- host/javascript/package.json
As I was updating examples for ValidationError I realised, we do have imports like this `@superfaceai/one-sdk/node`, but those didn't work. They required `@superfaceai/one-sdk/node/index.js`.
This PR corrects it, but the original way will work as well.
> fix(host-javascript): properly export esm modules

- host/javascript/package.json
Before I tested it, but obviously badly.
for backward compatibility `node/index.js` and `cloudflare/index.js` must be listed as well.
> Exports must include `node/index.js` for backward compatibility

- host/javascript/README.md
https://github.com/nodejs/node/pull/47286
WASI preview1 is enabled since node 18.17 and in node 20 be default.
This PR changes it to mention need for flag as note instead having it as mandatory.
I think this makes it less scary for use not familiar with WebAssembly and WASI.
> Mention WASI flag as note only

- .github/workflows/release.yml
- host/javascript/.gitignore
- host/python/.gitignore
Publishing to registry is separated from preparing repository.
This allows us to fix issues on our side and retry publishing. Even rollbacking prepared changes by CI/CD in repository and reruning publish pipeline.
Also creates GitHub release for pre-releases (alpha, beta, rc) and uses unreleased section of chagenlog as description of the release.
When at least one host was released it triggers [superface daily](https://github.com/superfaceai/superface-daily).
> Publishing is separated from repository prepare

- .github/workflows/release.yml
Instead of reruning script which uses already updated version, it uses outputs from prepare job.
> Fix release tag and version by taking it from other job

- host/javascript/src/node/index.test.ts
- host/javascript/src/node/index.ts
- host/javascript/src/node/wasm.ts
This solves an issue in POD, where we tried to load WASM file from within package.
It works for local development, same as using node.js OneClient. So I believe t will work. But perhaps I can publish manually experiement version from this branch, before adding it to main.
> Export function loading Core wasm file

- host/javascript/src/common/wasm.ts
- host/javascript/src/node/index.ts
Hopefully this will fix an issue where path contained disk label twice:
> Fix core path on windows

- examples/run.sh
- packages/nodejs_host/src/index.ts
- packages/python_host/src/one_sdk/client.py
- packages/python_host/src/one_sdk/platform.py
Allows disabling the automatic sending of metrics and on exit hooks. Metrics are still generated and need to be consumed periodically - this might need to be changed later.
During initial performance testing (see #108) this was required but this usecase might be important, and it is already implemented for cloudflare host.
> feat: allow disabling autosending metrics

- core/Cargo.lock
This PR updates core dependencies to fix building on macOS Sonoma.
```
--- stderr
thread 'main' panicked at '"enum_(unnamed_at__/quickjs/quickjs_h_67_1)" is not a valid Ident', /Users/freaz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.53/src/fallback.rs:780:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [core/dist/core.wasm] Error 101
```
> chore(core): update dependencies

- core_js/map-std/src/internal/bytes.ts
- core_js/map-std/src/internal/node_compat.ts
- core_js/map-std/src/map_std.ts
- core_js/map-std/src/unstable.ts
- examples/comlinks/src/communication.send-email.mailchimp.map.js
- examples/comlinks/src/communication.send-sms.twilio.map.js
- examples/comlinks/src/communication.send-sms.tyntec.map.js
- examples/comlinks/src/wasm-sdk.example.localhost.map.js
* made MapError generic over the value it stores
* made UsecaseContext and UsecaseFn generic over input, result and error
* export MapError and AnyValue types into the global namespace of the map-std types (this is sort of like stabilising them, but they are just types and we don't currently distribute those)
* correctly type Response.bodyJson and Response.bodyAuto (add Buffer into the possible return types)
* improve Buffer.from to also accept Bytes
* update example maps with more correct typings
* fix provider parameters type to only string values
* fix FetchOptions.body type to AnyValue
Some improvements I realized can be useful as I was experimenting with TypeScript profiles
> feat: improve map-std types

- core/core/src/sf_core.rs
- core/core/src/sf_core/cache.rs
- core/core/src/sf_core/profile_validator.rs
* associated consts need an explicit lifetime
Just a fix for warnings/deprecations that started appearing with rust 1.74
> chore: fix rust 1.74 warning

- packages/nodejs_host/src/index.ts
Using `createRequire`, caused problems when OneSDK was bundled for use on Vercel. This way, hopefully, it will properly resolve the URL to file and include it in the bundle.
Needs to be tested, but I don't see better way then publishing it and actually building on Vercel because bulding locally works.
> Use readFileSync to load package json instead of createRequire

- core/comlink/src/typescript_parser/parser.rs
- core/comlink/tests/fixtures/typescript_profile/p1.profile.json
- core/comlink/tests/fixtures/typescript_profile/p1.profile.ts
- examples/comlinks/package.json
- examples/comlinks/src/wasm-sdk.example.profile.ts
- packages/nodejs_comlink/src/index.test.ts
* Profile parser was emitting AnyValue into all input and output schemas, but it only has to appear in schemas which make use of it
> feat: don't emit AnyValue in UseCase schema when unused

- core/interpreter_js/src/core_to_map_bindings/mod.rs
- core/interpreter_js/src/core_to_map_bindings/unstable.rs
- core_js/core-ffi/ffi.d.ts
- core_js/map-std/src/internal/bytes.ts
- core_js/map-std/src/internal/message.ts
- core_js/map-std/src/internal/node_buffer.ts
- core_js/map-std/src/internal/types.ts
- core_js/map-std/src/map_std.ts
- core_js/map-std/src/unstable.ts
* add `HttpResponse.bodyBuffer()`
* add `Buffer.concat()`
* add `Buffer.length`
* add new encoding `base64url` which uses urlsafe alphabet
> feat: improve map-std to allow handling multipart bodies

- core/Cargo.lock
- core/core_to_map_std/src/unstable/security.rs
- core/json_schemas/Cargo.toml
* support indexing into arrays when doing apikey security in body
I ran into this when researching Odoo tool, it uses jsonrpc and needs to inject the secret into the JSON body somehow, but we didn't support indexing into arrays.
> feat: apikey security in body - arrays
