examples/cloudflare_worker/src/index.ts, examples/node_js/index.mjs, examples/run.sh, host/js/src/cloudflare/index.ts, host/js/src/node/index.test.ts, host/js/src/node/index.ts
This is to be aligned with original implementation.
=> Node.js Client is called SuperfaceClient

.github/ISSUE_TEMPLATE/BUG_TEMPLATE.md, .github/ISSUE_TEMPLATE/QUESTION_TEMPLATE.md, .github/pull_request_template.md, README.md, docs/CODE_OF_CONDUCT.md, docs/CONTRIBUTING.md, docs/SECURITY.md, host/js/.gitignore, host/js/README.md, host/js/package.json
This PR changes: 
- main readme spli to contributing.md and readme.md
- adds issue and PR templates
- adds Security.md mentioning how we use secrets from user
- adds readme for js package so the [OneSDK](https://www.npmjs.com/package/@superfaceai/one-sdk/v/3.0.0-alpha.6) page on npmjs.com isn't empty
- Includes LICENSE file for JS host
- Add code of conduct, used GitHub template of https://www.contributor-covenant.org/version/2/0/code_of_conduct.html
---
=> Repo community standards

.github/workflows/ci_cd.yml, .github/workflows/release.yml
* even when toml changes we can restore the cache to get at least the registry index
=> feat: restore cargo cache when toml changes

host/js/src/common/app.ts
When too big data are read, it is split to chunks, which are then returned on every read.
For payload bigger than buffer, only buffer size was passed, which caused incomplete response payloads.
=> fix(host-js): read other chunks

core/host_to_core_std/src/unstable/http.rs
* only status and headers
* body is not read just for logging
=> fix: add http response to user log

core/core/src/mock.rs, core/core/src/observability/mod.rs, core/core/src/sf_core.rs, core/host_to_core_std/src/unstable/perform.rs, examples/cloudflare_worker/src/index.ts, examples/cloudflare_worker/yarn.lock, host/js/src/cloudflare/index.ts
* instead of panic produce an error
* also route stderr into console.error in cloudflare host
=> feat: improve take input error

core/core/src/observability/metrics.rs, host/js/src/cloudflare/index.ts, host/js/src/node/index.ts
* comment out Panic metric - it will get logged into the devlog but not sent with other metrics
* send metrics to batch endpoint instead of one by one
=> feat: use metrics batch endpoint

Makefile
* latest changes in Makefile broke clean async core build
* also tweak the makefile so that strip flags are only passed to wasm-opt when CORE_PROFILE == release
=> fix: Makefile core async build

.github/workflows/release.yml
=> fix(ci-cd): step from which to get RELEASE_VERSION

.github/workflows/release.yml
Several fixes in python release pipeline.
=> fix(ci-cd): sevaral fixes in release python

examples/python/__main__.py
Adds localhost server to mirror request
=> Add local server

core/core/src/lib.rs, core/core/src/sf_core/exception.rs
* perform exceptions (UnexpectedErrors) are now logged into the user log at Error level
=> feat: add unexpected errors to user log

Makefile, examples/node_js/index.mjs, examples/python/__main__.py, host/js/README.md, host/js/src/node/index.ts, host/python/README.md, host/python/src/one_sdk/__init__.py
- js: reexports PerformError and UnexptedError
- js: Updates example and readme section with error handling
- py: exports PerformError
- py: Updates examples and readme section with error handling
=> Fix errors export and examples how to handle errors

core/core/src/sf_core.rs, core/core/src/sf_core/exception.rs, core/core/src/sf_core/json_schema_validator.rs
This PR fixes incomplete implementation for validation errors.
Also improves how validation error is printed
=> Better JSON schema validation errors

core/host_to_core_std/src/unstable/http.rs
=> Remove dead code annotation and simpler into_body

README.md, core/Cargo.lock, core/core/Cargo.toml, core/core/src/lib.rs, core/core/src/mock.rs, core/core/src/observability/mod.rs, core/core/src/sf_core.rs, core/core/src/sf_core/cache.rs, core/core/src/sf_core/config.rs, core/core/src/sf_core/map_std_impl/mod.rs, core/core/src/sf_core/map_std_impl/stream.rs, core/core/src/sf_core/profile_validator.rs, core/host_to_core_std/src/fmt.rs, core/host_to_core_std/src/lib.rs, core/host_to_core_std/src/unstable/http.rs, examples/cloudflare_worker/src/index.ts, examples/run.sh, host/javascript/README.md, host/javascript/package.json
* clean up ENV vars into one place
* change ONESDK_LOG to only be on/off
* implement PeekableStream
* do not log TRACE into developer dump log
=> feat: body logging for user log

core/CHANGELOG.md, core/core/src/sf_core/json_schema_validator.rs, core/json_schemas/src/schemas/security_values.json, core/json_schemas/src/schemas/security_values.yaml
Discovered when implementing Daily tests. Json Schema was missing required properties.
https://github.com/superfaceai/superface-daily/actions/runs/5832563218/job/15818359478#step:5:280
=> Fix security validation for missing property

examples/python/__main__.py
Just a small change of Python usage example
=> fix: make python example more Pythonic

.github/workflows/release.yml
* host releases now wait for each other due to push race condition happening otherwise
=> fix: make host releases serial

host/python/README.md
=> More pythonic example in docs

core/core/src/mock.rs, core/core/src/sf_core.rs, examples/node_js/index.mjs, examples/python/__main__.py, host/javascript/README.md, host/javascript/src/common/app.test.ts, host/javascript/src/common/app.ts, host/javascript/src/common/error.ts, host/javascript/src/node/index.ts, host/python/README.md, host/python/src/one_sdk/__init__.py, host/python/src/one_sdk/app.py, host/python/src/one_sdk/error.py, host/python/tests/test_app.py
ValidationError is thrown from perform
Easier for end user to distinquish errors.
=> OneClient throws validation error

host/javascript/package.json, host/javascript/src/common/index.ts, host/javascript/src/node/index.ts
This PR adds javascript host exports to package.json file required for custom OneClient implementation.
=> feat: Add javascript host exports

.github/workflows/release.yml
- remove wrongly doubled argument
- prepare fr python and js run serially to avoid issue in syncing who poushes to repository first
=> Fixes for release pipeline

.github/workflows/release.yml, examples/comlinks/package.json, examples/comlinks/yarn.lock, scripts/build-a-core/template.py
There are few places where I missed renames.
=> Missed renamed places

packages/cloudflare_worker_host/README.md
- renamed shield
- and fixes in readme for CF worker
=> Restructure fixes vol. 2

examples/comlinks/src/wasm-sdk.example.localhost.map.js, packages/javascript_common/src/app.ts, packages/nodejs_host/src/index.test.ts, packages/python_host/tests/echo_server.py, packages/python_host/tests/test_one_client.py, scripts/build-a-core/cores.json, scripts/build-a-core/template.py
* NodeJS host was failing when fetch request returned an empty body
* Python handles this okay
* Normalized so that the core always gets a stream, but when the body is empty the stream reads 0 bytes
=> fix: http response empty body

Makefile, examples/cloudflare_worker/src/comlinks.ts, examples/cloudflare_worker/src/index.ts
* also update Makefile build_core_json_schemas to work with wasmtime 14.0 cli
=> chore: add wasm-sdk/example to cloudflare example

core_js/map-std/src/unstable.ts
* accept text/plain content-type
* allow any content type as long as Buffer is passed as body
=> feat: improve map-std fetch implementation

packages/map_std/README.md
Forgot to add a readme to the map-std package
=> chore: add map_std package readme

Makefile, core/Cargo.lock, core/core/src/sf_core/config.rs, core/interpreter_js/Cargo.toml, core/interpreter_js/src/core_to_map_bindings/mod.rs, core/interpreter_js/src/core_to_map_bindings/unstable.rs, core/interpreter_js/src/lib.rs, packages/javascript_common/src/app.ts
tracking work on fixing #122
Most of the work is in the Javy fork here https://github.com/superfaceai/javy, the diff is this https://github.com/bytecodealliance/javy/compare/main...superfaceai:javy:main
I'll do more cleanup on the fork (to get the tests to pass)
=> fix: javy quickjs leaking all values, causing crashes

core/core/src/observability/buffer/ring.rs
* when writing data longer than the buffer that gets split by the writer (tracing) the ring buffer would panic
* this was because it couldn't find event boundary to free data up to
* now if all previous events are exhausted we truncate the current in-progress event from the left (start)
=> fix: ring buffer panic when writing split data and overflow

packages/nodejs_comlink/src/index.ts, packages/nodejs_host/src/index.ts
* somehow there are two different `URL` classes when bundled for nextjs and we are getting and error at runtime from `fileURLToPath`
* this ensures we never give node APIs URLs, but construct the URL so that bundlers will bundle the asset
* it should also work without a bundler thanks to import.meta.url
=> fix: bundlers, URL class and asset bundling

packages/nodejs_comlink/src/index.ts, packages/nodejs_host/src/index.ts
* this time maybe it will work for both bundled and unbundled code
* and also on windows probably perhaps
=> fix: asset imports

core/Cargo.lock, core/interpreter_js/Cargo.toml, examples/comlinks/src/communication.send-email.mailchimp.map.js, examples/comlinks/src/communication.send-sms.twilio.map.js, examples/comlinks/src/communication.send-sms.tyntec.map.js, examples/comlinks/src/wasm-sdk.example.localhost.map.js, examples/comlinks/src/wasm-sdk.example.profile.ts
* also correct typos in examples
=> chore: update Javy dependency
